[package]
name = "boa-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
boa_engine = { version = "0.17", features = ["annex-b"] }
boa_gc = { version = "0.17", features = ["thinvec"] }
boa_runtime = "0.17"
